GET http://localhost:8080/backendstart/api/info

###
POST http://localhost:8080/backendstart/api/login
Content-Type: application/json

{
  "username": "admin",
  "password": "test123"
}
###
GET http://localhost:8080/backendstart/api/info/user
x-access-token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiYWRtaW4iLCJleHAiOjE2ODIwMTUwMzUsImlhdCI6MTY4MjAxMzIzNSwiaXNzdWVyIjoic2VtZXN0ZXJzdGFydGNvZGUtZGF0MyIsInVzZXJuYW1lIjoiYWRtaW4ifQ.XY_HDCOubMGPK1esmf15SrWx5cnY7STkf6kFxYJ8qv8

###
POST http://localhost:8080/backendstart_war_exploded/api/festival/create
Content-Type: application/json
{
"name": "Arsim",
"city": "Valby",
"startDate": "23/4"
"duration": "2 timer"
}
###
GET http://localhost:8080/backendstart_war_exploded/api/festival/all

###
PUT http://localhost:8080/backendstart_war_exploded/api/festival/update
{
"id": 0,
"name": "smallman",
"city": "Hvidovre",
"duration": "2 timer",
"startDate": "27/4"
}

###
POST http://localhost:8080/backendstart_war_exploded/api/show/create
Content-Type: application/json
{
"name": "muuu",
"duration": "1 time",
"location": "Hvidovre",
"startDate": "27/5"
}