GET http://localhost:8080/backend_start/api/info

###
POST http://localhost:8080/backend_start/api/login
Content-Type: application/json

{
  "username": "admin",
  "password": "test123"
}
###
GET http://localhost:8080/backend_start/api/info/admin
x-access-token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiYWRtaW4iLCJleHAiOjE2ODE4NDE5NzUsImlhdCI6MTY4MTg0MDE3NSwiaXNzdWVyIjoic2VtZXN0ZXJzdGFydGNvZGUtZGF0MyIsInVzZXJuYW1lIjoiYWRtaW4ifQ.GVmeH3rMmP6JkwuxPINBAV0xH-wYze_b_--k4lc8nls